LibraryManagementSystem/ViewModels/Barcodes/BarcodesDeleteBarcodeVM.cs
using System;

namespace LibraryManagementSystem.ViewModels.Barcodes
{
    public class BarcodesDeleteBarcodeVM
    {
        public int ID { get; set; }
        public int BarcodeNumber { get; set; }
    }
}

LibraryManagementSystem/ViewModels/Barcodes/BarcodesEditBarcodeVM.cs
using System;
using System.Web.WebPages.Html;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using LibraryManagementSystem.DataAccess.Entities;

namespace LibraryManagementSystem.ViewModels.Barcodes
{
    public class BarcodesEditBarcodeVM
    {
        public int ID { get; set; }

        [DisplayName("Barcode")]
        [Required(ErrorMessage = "* barcode required")]
        public int BarcodeNumber { get; set; }      
        
        public virtual int BookID { get; set; }               
    }
}

LibraryManagementSystem/Controllers/BarcodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryManagementSystem.Models;
using LibraryManagementSystem.Filters;
using LibraryManagementSystem.ViewModels.Books;
using LibraryManagementSystem.ViewModels.Barcodes;
using LibraryManagementSystem.ViewModels.Pager;
using LibraryManagementSystem.DataAccess.Entities;
using LibraryManagementSystem.DataAccess.Repositories;
using LibraryManagementSystem.DataAccess.DataAccessLayer;
using DataAccess;

namespace LibraryManagementSystem.Controllers
{
    [AuthenticationFilter]
    public class BarcodesController : BaseController
    {        
        public ActionResult EditBarcode(int id, int bookID)
        {
            LibraryManagementSystemContext context = new LibraryManagementSystemContext();
            BarcodesRepository barcodesRepository = new BarcodesRepository(context);
            BooksRepository booksRepository = new BooksRepository(context);
            BarcodesEditBarcodeVM model = new BarcodesEditBarcodeVM();

            Barcode barcode = barcodesRepository.GetByID(id);
            if (id > 0)
            {
                if (barcode == null)
                {
                    barcode.BookID = bookID;                    
                }

                model.ID = barcode.ID;
                model.BookID = barcode.BookID;
                model.BarcodeNumber = barcode.BarcodeNumber;                
            }     

            return View(model);
        }

        [HttpPost]
        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        public ActionResult EditBarcode(BarcodesEditBarcodeVM model)
        {
            LibraryManagementSystemContext context = new LibraryManagementSystemContext();
            BarcodesRepository barcodesRepository = new BarcodesRepository(context);            

            Barcode barcode = null;
            if (barcodesRepository.GetAll().Any(b => b.BarcodeNumber == model.BarcodeNumber) &&
                model.ID != barcodesRepository.GetAll(filter: b => b.BarcodeNumber == model.BarcodeNumber).FirstOrDefault().ID)
            {
                ModelState.AddModelError("BarcodeNumber", "* barcode already exists");   
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                if (model.ID > 0)
                {
                    barcode = barcodesRepository.GetByID(model.ID);
                }
                else
                {
                    barcode = new Barcode();
                }

                barcode.ID = model.ID;
                barcode.BookID = model.BookID;
                barcode.BarcodeNumber = model.BarcodeNumber;

                barcodesRepository.Save(barcode);
            }

            return RedirectToAction("ListBookBarcodes/" + barcode.BookID, "Books");
        }

        public ActionResult DeleteBarcode(int id)
        {
            LibraryManagementSystemContext context = new LibraryManagementSystemContext();
            BarcodesRepository barcodesRepository = new BarcodesRepository(context);
            BarcodesDeleteBarcodeVM model = new BarcodesDeleteBarcodeVM();

            Barcode barcode = barcodesRepository.GetByID(id);
            model.ID = barcode.ID;
            model.BarcodeNumber = barcode.BarcodeNumber;

            return View(model);
        }

        [HttpPost]
        public ActionResult DeleteBarcode(BarcodesDeleteBarcodeVM model)
        {
            LibraryManagementSystemContext context = new LibraryManagementSystemContext();
            BarcodesRepository barcodesRepository = new BarcodesRepository(context);

            Barcode barcode = barcodesRepository.GetByID(model.ID);
            if (barcode == null)
            {
                return HttpNotFound();
            }
            else
            {
                barcodesRepository.Delete(barcode);
            }

            return RedirectToAction("ListBookBarcodes/" + barcode.BookID, "Books");
        }
    }
}

LibraryManagementSystem/Views/Barcodes/DeleteBarcode.cshtml
@model LibraryManagementSystem.ViewModels.Barcodes.BarcodesDeleteBarcodeVM

@{
    ViewBag.Title = "Delete " + "\"" + Model.BarcodeNumber + "\"";
}

<br /><hr />
<h3>Are you sure you want to delete barcode "@Model.BarcodeNumber"?</h3><hr />
<div>    
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" style="width:100px;" />             
        </div>
    }
</div>

LibraryManagementSystem/Views/Barcodes/EditBarcode.cshtml
@model LibraryManagementSystem.ViewModels.Barcodes.BarcodesEditBarcodeVM

@{
    if (Model.ID > 0)
    {
        ViewBag.Title = "Edit barcode";
        <h3>Edit barcode</h3>
    }
    else
    {
        ViewBag.Title = "Add barcode";
        <h3>Add barcode</h3>
    }
}
<hr />

@using (Html.BeginForm("EditBarcode", "Barcodes", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID)
    <div class="form-horizontal">               
        <div class="col-xs-10 col-md-4">
            <div style="margin-left: 30px;">
                <div class="form-group">
                    @Html.LabelFor(model => model.BarcodeNumber, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.BarcodeNumber, " ", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BarcodeNumber, null, new { @style = "color:red;!important" })
                </div>  
                
                <div class="form-group">
                    <input type="submit" style="width:100px;" value="Save" class="btn btn-success" />
                </div>              
            </div>
        </div>
    </div>   
}  